### ISSUE TITLE
IOS 消息推送二次进去无法启用

### ISSUE THREAD

**Issue by xiaokaike** [bestv2/react-native-aliyun-onesdk#2]
https://github.com/bestv2/react-native-aliyun-onesdk/blob/master/ios/AliPushManager.m#L296

```
if([CloudPushSDK getDeviceId] != nil){
		_requestPermissionsResolveBlock([CloudPushSDK getDeviceId]);
		_requestPermissionsResolveBlock = nil;
		_requestPermissionsRejectBlock = nil;
	}else {
		// SDK初始化
		NSString *appKey = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"com.alibaba.app.appkey"];
		NSString *appSecret = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"com.alibaba.app.appsecret"];
//		NSLog(@"appKey:%@,appSecret:%@",appKey,appSecret);
		[CloudPushSDK asyncInit:appKey appSecret:appSecret callback:^(CloudPushCallbackResult *res) {
		if (res.success) {
			_requestPermissionsResolveBlock(self.deviceId);
		} else {
			_requestPermissionsRejectBlock(@"0",@"初始化失败",@"");
		}
		_requestPermissionsResolveBlock = nil;
		_requestPermissionsRejectBlock = nil;
	}];
```

二次进去的时候 存在 `[CloudPushSDK getDeviceId] ` 所以不会进去到else 里面，导致 没有调用 `CloudPushSDK asyncInit` 倒是消息推送 不在线 无法收到

**Comment by bestv2** [comment]
@xiaokaike 二次进去是什么意思？

**Comment by xiaokaike** [comment]
就是删除app进程 然后重新打开

**Comment by bestv2** [comment]
@xiaokaike 这样应该是没有问题的，如果[CloudPushSDK getDeviceId]存在的时候去调用 asyncInit会报错，说SDK已经初始化成功，你再试一下，就算杀掉app再打开，用阿里云推送后台看还是在线状态的

**Comment by xiaokaike** [comment]
不 asyncInit 也会发起长连接？

**Comment by bestv2** [comment]
@xiaokaike 不好意思 重新看了下，我现在是在 AppDelegate中执行 asyncInit方法，放在AliPushManagaer中执行，放在AliPushManager中执行，有时候有点问题，你也也可以在 didFinishLaunchingWithOptions 中执行
- (void)initCloudPush {
	// SDK初始化
	NSString *appKey = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"com.alibaba.app.appkey"];
	NSString *appSecret = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"com.alibaba.app.appsecret"];
	
	[CloudPushSDK asyncInit:appKey appSecret:appSecret callback:^(CloudPushCallbackResult *res) {
				NSLog(@"=========initCloudPush %@",[CloudPushSDK getDeviceId]);

		if (res.success) {
			
		} else {
			
		}
//		[AliPushManager didRegisterForAliDevice:[CloudPushSDK getDeviceId]];
	}];
}
等有时间，我再看看AlipushManager中的问题，该一下，现在可以先用上面的方法处理着。

**Comment by bestv2** [comment]
@xiaokaike 不好意思 重新看了下，我现在是在 AppDelegate中执行 asyncInit方法，放在AliPushManagaer中执行，放在AliPushManager中执行，有时候有点问题，你也也可以在 didFinishLaunchingWithOptions 中执行
```
- (void)initCloudPush {
	// SDK初始化
	NSString *appKey = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"com.alibaba.app.appkey"];
	NSString *appSecret = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"com.alibaba.app.appsecret"];
	
	[CloudPushSDK asyncInit:appKey appSecret:appSecret callback:^(CloudPushCallbackResult *res) {
				NSLog(@"=========initCloudPush %@",[CloudPushSDK getDeviceId]);

		if (res.success) {
			
		} else {
			
		}
//		[AliPushManager didRegisterForAliDevice:[CloudPushSDK getDeviceId]];
	}];
}
```
等有时间，我再看看AlipushManager中的问题，该一下，现在可以先用上面的方法处理着。

**Comment by xiaokaike** [comment]
好的

**Comment by xiaokaike** [comment]
还有一个问题请教下，每次我 `react-native run-android` 都会有长时间的构建
```sh
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
> Configuring > 4/5 projects > Resolving dependencies ':react-native-aliyun-onesdk:_debugPublish'
```
gradlew 停留在 _debugPublish 很长时间，有什么办法可以解决么？

**Comment by bestv2** [comment]
@xiaokaike build.gradle 里面  
```
repositories {
    maven {
        // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
        url "$projectDir/../../../node_modules/react-native/android"
    }
    maven { url "http://maven.aliyun.com/nexus/content/groups/public/" }

    maven { url "https://jitpack.io" }
    mavenLocal()
    jcenter()
}
```
以前配置里面有个maven库打不开了，替换了一个aliyun的

**Comment by bestv2** [comment]
以前配置里面有个maven库打不开了，替换了一个aliyun的
