### ISSUE TITLE
安卓环境下build报语法错误

### ISSUE THREAD

**Issue by mebtte** [bestv2/react-native-aliyun-onesdk#3]
\node_modules\react-native-aliyun-onesdk\android\src\main\java\aliyun\wind\onesdk\push\AliPushPacka
ge.java:18: 错误: AliPushPackage不是抽象的, 并且未覆盖ReactPackage中的抽象方法createJSModules()
public class AliPushPackage implements ReactPackage {

\node_modules\react-native-aliyun-onesdk\android\src\main\java\aliyun\wind\onesdk\push\AliPushH
elper.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误
:react-native-aliyun-onesdk:compileReleaseJavaWithJavac FAILED

**Comment by bestv2** [comment]
@mebtte 请使用最新版本的已经处理了，rn-0.47 package中不再需要createJSModules这个方法了
